# 接続先URL
# docker-composeでサービス名が「db」、DB名が「mydatabase」なので以下のようになります
spring.datasource.url=jdbc:postgresql://db:5432/mydatabase
# ユーザー名とパスワード（docker-composeのenvironmentに合わせる）
spring.datasource.username=user
spring.datasource.password=password

# MyBatisの設定
# エンティティクラス（TaskEntityなど）があるパッケージを指定（SQL内でクラス名を省略できます）
mybatis.type-aliases-package=com.example.demo.todo.model

# SQLが書かれたXMLファイルの場所を指定
mybatis.mapper-locations=classpath:mapper/*.xml

# キャメルケースの自動変換（DBの task_id を Javaの taskId に紐付け）
mybatis.configuration.map-underscore-to-camel-case=true

# SQLスクリプトの実行を有効にする
spring.sql.init.mode=always

spring.thymeleaf.cache=false

logging.level.com.example.todo.repository=DEBUG

spring.mvc.hiddenmethod.filter.enabled=true