version: '3.8'
services:
  app:
    image: mcr.microsoft.com/devcontainers/java:17-bullseye
    volumes:
      - ..:/workspaces/${localWorkspaceFolderBasename}:cached
    network_mode: service:db
    user: vscode
    command: sleep infinity

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"